name: Create icons for macOS
on: workflow_dispatch

jobs:
  create-macos-icons:
    name: Create icons for macOS
    runs-on: macos-26
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create icon
        run: ./png_to_icns.sh
        env:
          arch: arm64

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: macos-icons
          path: icons.icns