name: Deploy (Linux)
on: workflow_dispatch

jobs:
  deploy-macos:
    name: Deploy (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout
          uses: actions/checkout@main
          
      - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '8.0.x'
            
      - name: Velopack Setup
          run: dotnet tool install -g vpk
          
      - name: Fork App Repository
          run: git clone https://github.com/BoomboxRapsody/NekoPlayer
            
      - name: Pre-builder Setup 
          run: dotnet build NekoPlayer-deploy.sln
            
      - name: Build
          run: ./bin/Debug/net8.0/NekoPlayer.Desktop.Deploy.exe
    
      - name: Upload
          uses: actions/upload-artifact@v4
          with:
            name: macos-release
            path: ./bin/Debug/net8.0/releases/
